//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGuardian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataGuardian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New_backup_{0}.
        /// </summary>
        internal static string Str_BackupManager_BackupName {
            get {
                return ResourceManager.GetString("Str_BackupManager_BackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during perform Local files check.
        /// </summary>
        internal static string Str_BackupManager_CronJobError {
            get {
                return ResourceManager.GetString("Str_BackupManager_CronJobError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not restored, please check.
        /// </summary>
        internal static string Str_BackupManager_DataNotRestored {
            get {
                return ResourceManager.GetString("Str_BackupManager_DataNotRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data restored successfully.
        /// </summary>
        internal static string Str_BackupManager_DataRestoredSuccessfully {
            get {
                return ResourceManager.GetString("Str_BackupManager_DataRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems local version of &apos;{0}&apos; - [{1}] missing.{2}Do you want to restore it from last remote backup?.
        /// </summary>
        internal static string Str_BackupManager_LocalVersionMissing {
            get {
                return ResourceManager.GetString("Str_BackupManager_LocalVersionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local version is missing: &apos;{0}&apos;, need to restore {1} from remote copy.
        /// </summary>
        internal static string Str_BackupManager_LocalVersionMissingLog {
            get {
                return ResourceManager.GetString("Str_BackupManager_LocalVersionMissingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name and path for your backup script.
        /// </summary>
        internal static string Str_BackupManager_PleaseEnterName {
            get {
                return ResourceManager.GetString("Str_BackupManager_PleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of backup: &apos;{0}&apos;.
        /// </summary>
        internal static string Str_BackupManager_StartBackup {
            get {
                return ResourceManager.GetString("Str_BackupManager_StartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete backup, error: {0}.
        /// </summary>
        internal static string Str_WndRemoteBackups_CannotDeleteRemote {
            get {
                return ResourceManager.GetString("Str_WndRemoteBackups_CannotDeleteRemote", resourceCulture);
            }
        }
    }
}
